---
title: "County Median Listing Price All Homes"
output: html_notebook
---

```{r}
# Load libraries
library(dplyr)
library(readr)
library(readxl)
library(tidyr)
library(filesstrings)
```

```{r}
df <- read.csv('http://files.zillowstatic.com/research/public/County/County_MedianListingPrice_AllHomes.csv')
head(df)
```

```{r}
df_nc <- filter(df, State == 'NC')
head(df_nc)
```

```{r}
colnames(df_nc) <- sub("X","", colnames(df_nc))

head(df_nc)
```

```{r}
df_nc$MunicipalCodeFIPS <- sprintf("%03d", df_nc$MunicipalCodeFIPS)

```

```{r}
head(df_nc)
```

```{r}
df_nc$MunicipalCodeFIPS <- as.character(df_nc$MunicipalCodeFIPS)
df_nc$StateCodeFIPS <- as.character(df_nc$StateCodeFIPS)
head(df_nc)
```

```{r}
rownames(df_nc) <- df_nc$RegionName
head(df_nc)
```

```{r}
df_nc <- select(df_nc, -RegionName)
```

```{r}
df_nc[is.na(df_nc)] <- 0

head(df_nc)
```


```{r}
write.table(df_nc, file="STG_ZLLW_County_MedianListingPrice_AllHomes.txt", sep='\t')
```

```{r}
file.move("STG_ZLLW_County_MedianListingPrice_AllHomes.txt", "../Updates/", overwrite=TRUE)
```