# Generated by Django 2.0.6 on 2018-11-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20181106_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='TransactionType',
            new_name='topic',
        ),
    ]
