# Generated by Django 2.0.6 on 2018-11-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_auto_20181107_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionType',
            new_name='text',
        ),
    ]
