# Generated by Django 2.0.6 on 2018-11-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_auto_20181107_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='text',
            new_name='TransactionType',
        ),
    ]
