# Generated by Django 2.0.6 on 2018-11-24 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionType',
            new_name='text',
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
