# Generated by Django 2.0.6 on 2018-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_auto_20181123_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='transaction_amount',
            field=models.FloatField(max_length=200),
        ),
    ]
