# Generated by Django 2.0.6 on 2018-11-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_auto_20181126_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
