# Generated by Django 2.0.6 on 2018-12-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0010_auto_20181128_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='transaction_amount',
            field=models.FloatField(max_length=10),
        ),
    ]
