# Generated by Django 2.0.6 on 2018-12-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_auto_20181203_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='merchant',
        ),
    ]
